yarnPath: .yarn/releases/yarn-4.5.1.cjs
supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"
  cpu:
    - "current"
    - "x64"
    - "x86"
    - "arm"
    - "arm64"
    - "ia32"
